spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://givy-db.craqig8oi76h.ap-northeast-2.rds.amazonaws.com:3306/givy?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${SPRING_DATASOURCE_USERNAME} # env파일 설정
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS}

oauth:
  kakao:
     client-secret: ${CLIENT_SECRET}