server:
  port: 8081

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/givy?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234 # 각자 로컬 DB 비번 사용
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create

  jwt:
    secret: ${JWT_SECRET:temp_secret_key_more_than_32_characters}
    expiration-ms: 3600000